### ISSUE TITLE
[Bug]: clip_vision broken in 1.1?

### ISSUE THREAD

**Issue by tkalayci71** [Mikubill/sd-webui-controlnet#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After updating to ControlNet 1.1, I get this error, when I use clip_vision + t2iadapter_style:

  File "C:\webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 104, in forward
    hint_in = hint_in.unsqueeze(0)
AttributeError: 'NoneType' object has no attribute 'unsqueeze'

I also tried no preprocessor  + t2iadapter_style, with a fake image I had saved earlier, same result.

I had renamed t2iadapter_style_sd14v1.yaml to t2iadapter_style-fp16.yaml, which used to work with Controlnet 1.0

My webui/controlnet installation is a bit messed up right now, apologies if this bug applies only to me. 

Thanks.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

worked

### Commit where the problem happens

webui: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
controlnet: b2a2d1a075dbfe78b5f64758bf0014a35ba558c8 ?

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--lowvram --always-batch-cond-uncond --autolaunch --xformers --clip-models-path ./models/clip/ --ckpt ./models/Stable-diffusion/analogMadness_analogMadnessV2.safetensors --use-cpu interrogate,codeformer
```

### Console logs

```Shell
Loading model from cache: t2iadapter_style-fp16 [0e2e8330]
Loading preprocessor: clip_vision
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(09jiuzjpb6nw17w)', '', '', ['default'], 8, 16, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 768, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, <scripts.external_code.ControlNetUnit object at 0x0000013AC252EB00>, <scripts.external_code.ControlNetUnit object at 0x0000013AC254DF60>, <scripts.external_code.ControlNetUnit object at 0x0000013AC254E3B0>, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\webui\modules\processing.py", line 836, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\webui\modules\sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\webui\modules\sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\modules\sd_samplers_kdiffusion.py", line 119, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "C:\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\extensions\sd-webui-controlnet\scripts\hook.py", line 253, in forward2
    return forward(*args, **kwargs)
  File "C:\webui\extensions\sd-webui-controlnet\scripts\hook.py", line 154, in forward
    control = param.control_model(x=x, hint=param.used_hint_cond, timesteps=timesteps, context=context)
  File "C:\webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 104, in forward
    hint_in = hint_in.unsqueeze(0)
AttributeError: 'NoneType' object has no attribute 'unsqueeze'
```

**Comment by lllyasviel** [comment]
@Mikubill I do not know how to fix it

**Comment by lllyasviel** [comment]
fixed

**Comment by Arron17** [comment]
It is still working for me.
WebUI Commit: 22bcc7be428c94e9408f589966c2040187245d81
Control-Net Extension Commit: 0a9b46ef8d106539c89eddd1c043730dcefbe819

Looks like reporter is on an old Commit of the WebUI from March 14th.

However in the preview it now displays noise as the secondary image:
![image](https://user-images.githubusercontent.com/87210034/232257749-5ae0d7fc-03cd-494c-bc59-41542eb7744e.png)

**Comment by tkalayci71** [comment]
@lllyasviel Thank you.

@Arron17 Noise is deliberate, lets you reuse/share the clip_vision output
