### ISSUE TITLE
Issue with Latest Update - 6a5580ca (Mon Mar 13 11:58:34 2023)	

### ISSUE THREAD

**Issue by thenolifer** [Mikubill/sd-webui-controlnet#582]
After updating today to 6a5580ca (Mon Mar 13 11:58:34 2023) I get the following error;

`AttributeError: 'ControlNetUnit' object has no attribute 'get_image_dict'`

On all models.

**Comment by vegacosphoto** [comment]
same

**Comment by ljleb** [comment]
fixed in latest, change was reverted.
