### ISSUE TITLE
after updating to 1.436  get AttributeError: 'ControlModel' object has no attribute 'reset'

### ISSUE THREAD

**Issue by protector131090** [Mikubill/sd-webui-controlnet#2563]
2024-01-23 20:49:16,910 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
*** Error running process: C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1117, in process
        self.controlnet_hack(p)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\sd.webui\webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

**Comment by huchenlei** [comment]
File an issue in https://github.com/continue-revolution/sd-webui-animatediff please. `control_model_guess.py` is not supposed to be exposed, and we don't guarantee that the signature does not change.

Here the guess control model function returns a tuple instead of a single value now.
