### ISSUE TITLE
[Bug]: Except for the Canny model, all other models are giving errors.

### ISSUE THREAD

**Issue by DivineYun** [Mikubill/sd-webui-controlnet#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

In v1.1，Except for the canny model, all other models cannot be used and will always prompt that there is a problem with the model.

I have tried deleting the folder and re-downloading, as well as upgrading directly from an old version to a new version. Of course, I have also tried restarting the UI and even restarting the computer, but none of these have solved the problem.

I have posted the code here. Please take a look, experts.

### Steps to reproduce the problem

There are no special steps, the error occurs during normal usage. I have been using ControlNet for a long time before this, so there is no issue of not knowing how to use it.

1. Click "Enable" and "No Prompt Word Mode" (I only did this for testing purposes, even if there are prompt words, the error will still occur.)
2. Import the image.
3. Select the processor and model.
4. Adjust the image size.
5. Preview the processing result (an error will occur, please see the first paragraph of the error code below).
6. Click "Generate Image" (an error will occur, please see the second paragraph of the error code below).

### What should have happened?

none

### Commit where the problem happens

I have used two computers and tested with different versions of webui, but the same error occurred on both.
I use win11.

1、webui: python: 3.10.10  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.23.0 

2、webui: python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.23.0  
controlnet: v1.1

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
Launching Web UI with arguments: --autolaunch --xformers --no-half-vae --disable-nan-check
```

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

Installing sd-dynamic-prompts requirements.txt

Installing sd-webui-controlnet requirement: mediapipe==0.9.1.0

Installing sd-webui-controlnet requirement: opencv-python

Launching Web UI with arguments: --autolaunch --api --disable-nan-check
No module 'xformers'. Proceeding without it.

Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: F:\stable-diffusion-webui-master\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Error loading script: main.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui-master\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\stable-diffusion-webui-master\extensions\a1111-sd-webui-locon-main\scripts\main.py", line 10, in <module>
    import lora
ModuleNotFoundError: No module named 'lora'

[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

Loading weights [93a20525f5] from F:\stable-diffusion-webui-master\models\Stable-diffusion\二次元\colorBoxModel_colorBOX.safetensors
Creating model from config: F:\stable-diffusion-webui-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: F:\stable-diffusion-webui-master\models\VAE\animevae.pt
Applying cross attention optimization (Doggettx).
No Image data blocks found.
No Image data blocks found.
Textual inversion embeddings loaded(3): badhandv4, EasyNegative, ulzzang-6500-v1.1
Model loaded in 4.8s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.6s, apply half(): 0.6s, load VAE: 0.6s, move model to device: 0.5s, load textual inversion embeddings: 1.9s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.3s (import torch: 1.9s, import gradio: 1.1s, import ldm: 0.5s, other imports: 2.8s, list SD models: 0.1s, load scripts: 2.3s, load SD checkpoint: 5.1s, create ui: 5.0s, gradio launch: 0.3s).
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 393, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\processor.py", line 232, in openpose_full
    result = model_openpose(img, include_hand=True, include_face=True)
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 75, in __call__
    self.load_model()
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 64, in load_model
    self.hand_estimation = Hand(hand_modelpath)
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\openpose\hand.py", line 21, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "F:\stable-diffusion-webui-master\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "F:\stable-diffusion-webui-master\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\stable-diffusion-webui-master\py310\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 18285 more bytes. The file might be corrupted.

Error running process: F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 725, in process
    self.unloadable.get(key, lambda:None)()
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\processor.py", line 238, in unload_openpose
    model_openpose.unload_model()
  File "F:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 70, in unload_model
    self.hand_estimation.model.to("cpu")
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by lllyasviel** [comment]
the last time the controlnet when was downloading openpose, you stopped your webui before the downloading is finished. Your webui/models/openpose is corrupted. remove  "webui/models/openpose" and controlnet will download models again

**Comment by DivineYun** [comment]
> 上次 ControlNet 在下载 OpenPoPose 时，您在下载完成之前停止了 WebUI。您的 webui/models/openpose 已损坏。删除“webui/models/openpose”，Controlnet将再次下载模型

模型是在“huggingface”下载的呀，不是webui下载的，而且我已经在“huggingface”重复下载好几次了，无法解决这个问题。 @lllyasviel

**Comment by sanshaoyeyang** [comment]
same problem ,cant solve yet

**Comment by DivineYun** [comment]
Thank you very much! The problem has been resolved and can now be used normally.

The main reason for this problem may be that after updating to v11 and downloading the model, other models still need to be downloaded in the background to use the model normally. However, there is no download prompt on the WEBUI interface, and it takes some time to download. Only in the background can you see that something is downloading.

Especially, this file is not in the extensions folder, but in the models folder.

Therefore, many people may see no response from the plugin during the download process and perform other operations, which leads to download failure.

Another issue is that China's network cannot log in to "huggingface", which is also the reason why this problem occurs frequently in China.

It is hoped that the models that need to be downloaded separately can be merged or provided by "huggingface" with detailed instructions for use.

@lllyasviel @sanshaoyeyang

**Comment by sanshaoyeyang** [comment]
@DivineYun  请问你是如何解决的，我也删除了扩展文件重新安装了很多次，但是还是无法解决问题

**Comment by sanshaoyeyang** [comment]
@DivineYun  主要是后台也没有显示在下载文件，还是一样报错

**Comment by sanshaoyeyang** [comment]
@DivineYun  Thanks!i ll try

**Comment by lllyasviel** [comment]
should fix now.
update and completely restart
