### ISSUE TITLE
[Bug]: Error after startup

### ISSUE THREAD

**Issue by racinmat** [Mikubill/sd-webui-controlnet#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I installed the extension according to the instructions, but after reloading the UI, I got this error
```
Restarting UI...
Closing server running on port: 7860
ControlNet v1.1.186
ControlNet v1.1.186
Traceback (most recent call last):
  File "D:\Projects\image_generation\stable-diffusion-webui\launch.py", line 348, in <module>
    main()
  File "D:\Projects\image_generation\stable-diffusion-webui\launch.py", line 344, in main
    start()
  File "D:\Projects\image_generation\stable-diffusion-webui\launch.py", line 334, in start
    webui.webui()
  File "D:\Projects\image_generation\stable-diffusion-webui\webui.py", line 363, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\Projects\image_generation\stable-diffusion-webui\modules\ui.py", line 445, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "D:\Projects\image_generation\stable-diffusion-webui\modules\scripts.py", line 311, in initialize_scripts
    script = script_data.script_class()
  File "D:\Projects\image_generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 209, in __init__
    self.preprocessor = global_state.cache_preprocessors(global_state.cn_preprocessor_modules)
  File "D:\Projects\image_generation\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 22, in cache_preprocessors
    CACHE_SIZE = shared.cmd_opts.controlnet_preprocessor_cache_size
AttributeError: 'Namespace' object has no attribute 'controlnet_preprocessor_cache_size'
```

### Steps to reproduce the problem

1. Install it using the webui
2. Press Reload UI
3. error happens

### What should have happened?

install without error

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3605407033fa50408239924e77ccf38dcd5225b9
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/06515a669d4e95fd39a6fc68df1021ec50643002

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### List of enabled extensions

controlnet

### Console logs

```Shell
in thee error
```

### Additional information

it seems the error was introduced in commit https://github.com/Mikubill/sd-webui-controlnet/commit/c1aeca540e34cf619fa646b874bdb51ac6bbe8f5#diff-7bf611a9788e7c7b74c399f65cdb91ce3ae5e61db0eb2ce29c9cd7ef84e96e39R22 where option is read, but not added as cmd option

**Comment by RoyalAce22** [comment]
I am having the same issue.

**Comment by huchenlei** [comment]
Completely restart webui should fix the issue.

**Comment by HARUKAGUEN** [comment]
Hi I have done the complete restart of webUI, and then re-install ControlNet, it is still the same problem

**Comment by huchenlei** [comment]
> Hi I have done the complete restart of webUI, and then re-install ControlNet, it is still the same problem

You do not re-install ControlNet. After install ControlNet, the error occurs. You close the webui.bat terminal. Relaunch WebUI by clicking webui.bat. It should work fine.

**Comment by xarthurx** [comment]
> > Hi I have done the complete restart of webUI, and then re-install ControlNet, it is still the same problem
> 
> You do not re-install ControlNet. After install ControlNet, the error occurs. You close the webui.bat terminal. Relaunch WebUI by clicking webui.bat. It should work fine.

Yes, this works.

But this issue is definitely a bug, and we should find a way to fix it.

**Comment by Natotela** [comment]
temp workaround as instructed:
...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py
line 22
CACHE_SIZE = shared.cmd_opts.controlnet_preprocessor_cache_size
commented out & changed to 
CACHE_SIZE = 0

**Comment by mikecastrodemaria** [comment]
> temp workaround as instructed: ...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py line 22 CACHE_SIZE = shared.cmd_opts.controlnet_preprocessor_cache_size commented out & changed to CACHE_SIZE = 0

do the trick many thanks

**Comment by huchenlei** [comment]
> temp workaround as instructed: ...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py line 22 CACHE_SIZE = shared.cmd_opts.controlnet_preprocessor_cache_size commented out & changed to CACHE_SIZE = 0

Do note that by doing so you are disabling the caching layer. This will make preprocessor rerun even when you only changed the prompt.
