### ISSUE TITLE
[Bug]: Does not work in Gradio4 branch of Auto1111

### ISSUE THREAD

**Issue by Gushousekai195** [Mikubill/sd-webui-controlnet#2623]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The ControlNet extension does not load when using the Gradio4 branch of Auto1111 webui. It throws an error of `AttributeError: module 'gradio.components' has no attribute 'IOComponent'`

### Steps to reproduce the problem

1. `git checkout Gradio4`
2. `git pull`
3. Start the webui

### What should have happened?

ControlNet should have loaded normally

### Commit where the problem happens

webui: 43850655d9ba0e99f661981e0ac2007d47669634 (Gradio4 branch)
controlnet: 416c3450

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--no-half-vae --no-half --precision full --api --opt-sdp-attention --disable-nan-check --no-gradio-queue --enable-insecure-extension-access --port 7860
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/64454655/5d543953-2d4e-46c4-b904-1f7a6257d8b4)

### Console logs

```Shell
venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0-460-g43850655
Commit hash: 43850655d9ba0e99f661981e0ac2007d47669634
Launching Web UI with arguments: --no-half-vae --no-half --precision full --api --opt-sdp-attention --disable-nan-check --no-gradio-queue --enable-insecure-extension-access --port 7860
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-02-05 12:58:00,660 - ControlNet - INFO - ControlNet v1.1.440
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 23, in <module>
        from scripts.controlnet_ui.controlnet_ui_group import ControlNetUiGroup, UiControlNetUnit
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 33, in <module>
        class A1111Context:
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 36, in A1111Context
        img2img_batch_input_dir: Optional[gr.components.IOComponent] = None
    AttributeError: module 'gradio.components' has no attribute 'IOComponent'
```

**Comment by benlin924** [comment]
me too, how to fix this

**Comment by Jaid** [comment]
I just removed all references to `IOComponent` from the ControlNet extension’s code and restarted. Works without problems.

Seems not to have any side-effects, because all those references affect typing and not execution.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/6216144/eac4bb50-f2a2-4458-99ee-ca10e602dc58)
