### ISSUE TITLE
[Bug]: detected_maps won't auto save

### ISSUE THREAD

**Issue by TentacleCat** [Mikubill/sd-webui-controlnet#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I go to the Settings Tab, select the Controlnet. Then select the opinion "Allow detectmap auto saving", the path to save detected maps is default. 
I use t2i, input an image to Controlnet, Enable, Select "Depth". Then just generate an image. it didn't create any folder or processed image in the folder "extensions\sd-webui-controlnet\detected_maps"

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

It should create some folder likes "Depth" or "Openpose" in the folder "detected_maps" with some images.

### Commit where the problem happens

webui: 
python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  checkpoint: [828e5e0c31]
controlnet: 
v1.1.191

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/131333217/1e1e5298-c4cc-4fc3-a7e4-0982327f6d15)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/131333217/33658629-5abc-4c06-9a0b-a8bf234ceed0)

### Console logs

```Shell
venv "D:\Work\AI_Draw\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements

[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.



current transparent-background 1.2.3


Installing SD-CN-Animation requirement: scikit-image==0.19.2








If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.31.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.



Installing requirements for TemporalKit extension

Launching Web UI with arguments: --xformers --autolaunch --opt-channelslast --gradio-queue --api --opt-split-attention --autolaunch --no-half-vae
Error loading script: fix_names.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Work\AI_Draw\stable-diffusion-webui\scripts\fix_names.py", line 7, in <module>
    for filename in os.listdir(folder_path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/animation_video/animated_imgs_raw - Copy'

python_server_full_path:  D:\Work\AI_Draw\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\Work\AI_Draw\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
[-] ADetailer initialized. version: 23.5.18, num models: 7
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 62/62 [00:00<00:00, 30924.82it/s]
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 62/62 [00:00<00:00, 20666.52it/s]
ControlNet v1.1.193
ControlNet v1.1.193
Error loading script: temporalvideo.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\temporalvideo.py", line 95, in <module>
    output_images.append(send_request(x_path,y_folder, y_paths[0]))
IndexError: list index out of range

Error loading script: two_shot.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-latent-couple\scripts\two_shot.py", line 16, in <module>
    from modules.script_callbacks import CFGDenoisedParams, on_cfg_denoised, on_after_ui
ImportError: cannot import name 'on_after_ui' from 'modules.script_callbacks' (D:\Work\AI_Draw\stable-diffusion-webui\modules\script_callbacks.py)

Image Browser: ImageReward is not installed, cannot be used.
Loading weights [828e5e0c31] from D:\Work\AI_Draw\stable-diffusion-webui\models\Stable-diffusion\Anything-v3.0-For-Tachie\Anything-v3.0-For-Tachie.safetensors
Creating model from config: D:\Work\AI_Draw\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\Work\AI_Draw\stable-diffusion-webui\models\VAE\animevae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(4): badhandv4, EasyNegative, verybadimagenegative_v1.3, yaguru magiku
Textual inversion embeddings skipped(2): 21charturnerv2, re-badprompt
Model loaded in 3.9s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 0.6s, apply channels_last: 0.3s, apply half(): 0.5s, load VAE: 0.8s, move model to device: 0.8s).
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
*Deforum ControlNet support: enabled*
CUDA SETUP: Loading binary D:\Work\AI_Draw\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 43.4s (import torch: 4.2s, import gradio: 1.6s, import ldm: 0.7s, other imports: 1.2s, list SD models: 0.1s, setup codeformer: 0.1s, load scripts: 10.8s, load SD checkpoint: 4.3s, create ui: 19.3s, gradio launch: 1.0s, scripts app_started_callback: 0.1s).
Error running process: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 449, in process
    all_prompts, all_negative_prompts = generate_prompts(
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py", line 93, in generate_prompts
    all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]
  File "D:\Work\AI_Draw\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py", line 71, in generate
    prompts.append(next(iter(gen)))
StopIteration

Error running process: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 761, in process
    process_unit.set_process_attributes(p)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 87, in set_process_attributes
    inpaint_image, inpaint_mask = self.sam_inpaint_unit.get_input_and_mask(inpaint_mask_blur)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 43, in get_input_and_mask
    mask = Image.open(self.dilation_output_gallery[1]['name']).convert('L')
TypeError: 'UiControlNetUnit' object is not subscriptable

Error running process: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py", line 210, in process
    if targets_ is None or len(targets_) == 0:
TypeError: object of type 'bool' has no len()

Error running process: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py", line 131, in process
    weight = float(weight)
ValueError: could not convert string to float: 'Lerp'

Error running process: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 258, in process
    elemental = elemental.split("\n\n") if elemental is not None else []
AttributeError: 'list' object has no attribute 'split'

Error running process: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1031, in process
    self.enabled_units = self.get_enabled_units(p)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 990, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 842, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'int' object has no attribute 'enabled'

Error running process_batch: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 294, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
AttributeError: 'Script' object has no attribute 'lratios'

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.39it/s]
Error running postprocess: D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py0,  4.47it/s]
Traceback (most recent call last):
  File "D:\Work\AI_Draw\stable-diffusion-webui\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "D:\Work\AI_Draw\stable-diffusion-webui\extensions\sd-webui-llul\scripts\llul.py", line 236, in postprocess
    xi0 = int(x)
ValueError: invalid literal for int() with base 10: '0,0.25,0.5,0.75,1'

Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.85it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  4.47it/s]
```

### Additional information

The function works on Controlnet 1.0 and 1.1.179

**Comment by TentacleCat** [comment]
Fixed.
I disable all extensions and enable only some extensions. I guess some extensions may conflict.
Here's the extension list i enable and work well:

1. https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper
2. https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris
3. https://github.com/DominikDoom/a1111-sd-webui-tagcomplete
4. https://github.com/Bing-su/adetailer.git
5. https://github.com/s9roll7/ebsynth_utility
6. enhanced-img2img-main
7. https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git
8. https://github.com/adieyal/sd-dynamic-prompts
9. https://github.com/mcmonkeyprojects/sd-dynamic-thresholding
10. https://github.com/vladmandic/sd-extension-system-info
11. https://github.com/ClockZinc/sd-webui-IS-NET-pro
12. https://github.com/kohya-ss/sd-webui-additional-networks
13. **https://github.com/Mikubill/sd-webui-controlnet**
14. https://github.com/hnmr293/sd-webui-cutoff
15. https://github.com/hnmr293/sd-webui-llul
16. https://github.com/hako-mikan/sd-webui-lora-block-weight
17. https://github.com/hako-mikan/sd-webui-regional-prompter
18. https://github.com/continue-revolution/sd-webui-segment-anything
19. https://github.com/hako-mikan/sd-webui-supermerger
20. https://github.com/ashen-sensored/sd_webui_SAG
21. https://github.com/klimaleksus/stable-diffusion-webui-anti-burn
22. https://github.com/opparco/stable-diffusion-webui-composable-lora
23. https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor
